apiVersion: v1
kind: Service
metadata:
  name: mango-coupon
  namespace: mango
spec:
  type: ClusterIP
  selector:
    app: mango-coupon
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP