apiVersion: v1
kind: Secret
metadata:
  name: mango-secret
type: Opaque
stringData:
  SQL_USERNAME: "sa"
  SQL_PASSWORD: "Admin@786_123"

  AUTH_DB_CONNECTION: "Server=host.minikube.internal,1433;Database=Mango_Auth;User Id=sa;Password=Admin@786_123;TrustServerCertificate=true;Encrypt=False"
  PRODUCT_DB_CONNECTION: "Server=host.minikube.internal,1433;Database=Mango_Product;User Id=sa;Password=Admin@786_123;TrustServerCertificate=true;Encrypt=False"
  COUPON_DB_CONNECTION: "Server=host.minikube.internal,1433;Database=Mango_Coupon;User Id=sa;Password=Admin@786_123;TrustServerCertificate=true;Encrypt=False"
  EMAIL_DB_CONNECTION: "Server=host.minikube.internal,1433;Database=Mango_Email;User Id=sa;Password=Admin@786_123;TrustServerCertificate=true;Encrypt=False"
  ORDER_DB_CONNECTION: "Server=host.minikube.internal,1433;Database=Mango_Order;User Id=sa;Password=Admin@786_123;TrustServerCertificate=true;Encrypt=False"
  REWARD_DB_CONNECTION: "Server=host.minikube.internal,1433;Database=Mango_Reward;User Id=sa;Password=Admin@786_123;TrustServerCertificate=true;Encrypt=False"
  SHOPPINGCART_DB_CONNECTION: "Server=host.minikube.internal,1433;Database=Mango_ShoppingCart;User Id=sa;Password=Admin@786_123;TrustServerCertificate=true;Encrypt=False"

  JWT_SECRET: "THIS IS USED TO SIGN AND VERIFY JWT TOKENS, REPLACE IT WITH YOUR OWN SECRET"

  RABBITMQ_USERNAME: "guest"
  RABBITMQ_PASSWORD: "guest"