apiVersion: v1
kind: Secret
metadata:
  name: shoppingcartapi-secret
type: Opaque
stringData:
  Docker__ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=Mango_ShoppingCart;User Id=sa;Password=Admin@786_123;TrustServerCertificate=true;Encrypt=False"
  ApiSettings__Secret: "THIS IS USED TO SIGN AND VERIFY JWT TOKENS, REPLACE IT WITH YOUR OWN SECRET"
