apiVersion: v1
kind: ConfigMap
metadata:
  name: mangoweb-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_HTTP_PORTS: "8080"
  DOTNET_RUNNING_IN_CONTAINER: "true"
  Docker__ServiceUrls__AuthAPI: "http://authapi:8080"
  Docker__ServiceUrls__ProductAPI: "http://productapi:8080"
  Docker__ServiceUrls__ShoppingCartAPI: "http://shoppingcartapi:8080"
  Docker__ServiceUrls__CouponAPI: "http://couponapi:8080"
  Docker__ServiceUrls__OrderAPI: "http://orderapi:8080"
