apiVersion: v1
kind: Secret
metadata:
  name: mango-secrets
  namespace: mango
type: Opaque
stringData:
  Product__ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=Mango_Product;User Id=sa;Password=Admin@786_123;TrustServerCertificate=true;Encrypt=False"
  Coupon__ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=Mango_Coupon;User Id=sa;Password=Admin@786_123;TrustServerCertificate=true;Encrypt=False"
  Auth__ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=Mango_Auth;User Id=sa;Password=Admin@786_123;TrustServerCertificate=true;Encrypt=False"
  Order__ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=Mango_Order;User Id=sa;Password=Admin@786_123;TrustServerCertificate=true;Encrypt=False"
  Email__ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=Mango_Email;User Id=sa;Password=Admin@786_123;TrustServerCertificate=true;Encrypt=False"
  Reward__ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=Mango_Reward;User Id=sa;Password=Admin@786_123;TrustServerCertificate=true;Encrypt=False"

  ShoppingCart__ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=Mango_ShoppingCart;User Id=sa;Password=Admin@786_123;TrustServerCertificate=true;Encrypt=False"
  ShoppingCart__ApiSettings__Secret: THIS IS USED TO SIGN AND VERIFY JWT TOKENS, REPLACE IT WITH YOUR OWN SECRET

  Auth__ApiSettings__Secret: THIS IS USED TO SIGN AND VERIFY JWT TOKENS, REPLACE IT WITH YOUR OWN SECRET

  Coupon__ApiSettings__Secret: THIS IS USED TO SIGN AND VERIFY JWT TOKENS, REPLACE IT WITH YOUR OWN SECRET
  Email__MessageQueue__RabbitMQ__ConnectionString: amqp://guest:guest@host.docker.internal:5672