apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapi
  labels:
    app: orderapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderapi
  template:
    metadata:
      labels:
        app: orderapi
    spec:
      containers:
      - name: orderapi
        image: mango-orderapi-k8s:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: orderapi-config
        - secretRef:
            name: orderapi-secret
