apiVersion: apps/v1
kind: Deployment
metadata:
  name: mango-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mango-product
  template:
    metadata:
      labels:
        app: mango-product
    spec:
      containers:
        - name: mango-product
          image: mangoproductapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: DOTNET_RUNNING_IN_CONTAINER
              value: "true"

            - name: ApiSettings__Secret
              valueFrom:
                secretKeyRef:
                  name: mango-secret
                  key: JWT_SECRET

            - name: ApiSettings__Issuer
              valueFrom:
                configMapKeyRef:
                  name: mango-config
                  key: JWT_ISSUER

            - name: ApiSettings__Audience
              valueFrom:
                configMapKeyRef:
                  name: mango-config
                  key: JWT_AUDIENCE

            - name: Docker__ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: mango-secret
                  key: PRODUCT_DB_CONNECTION

            - name: Docker__ASPNETCORE_HTTP_PORTS
              value: "8080"
