apiVersion: apps/v1
kind: Deployment
metadata:
  name: productapi
  labels:
    app: productapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productapi
  template:
    metadata:
      labels:
        app: productapi
    spec:
      containers:
      - name: productapi
        image: mango-productapi-k8s:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: productapi-config
        - secretRef:
            name: productapi-secret
