apiVersion: apps/v1
kind: Deployment
metadata:
  name: mango-auth
  namespace: mango
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mango-auth
  template:
    metadata:
      labels:
        app: mango-auth
    spec:
      containers:
        - name: mango-auth
          image: mangoservicesauthapi:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef: 
                name: mango-common-config
                
          env:
            - name: ApiSettings__Secret
              valueFrom:
                secretKeyRef:
                  name: mango-secrets
                  key: Auth__ApiSettings__Secret  
                  
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: mango-secrets
                  key: Auth__ConnectionStrings__DefaultConnection