apiVersion: apps/v1
kind: Deployment
metadata:
  name: mango-order
  namespace: mango
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mango-order
  template:
    metadata:
      labels:
        app: mango-order
    spec:
      containers:
        - name: mango-order
          image: mangoservicesorderapi:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          
          envFrom:
            - configMapRef:
                name: mango-common-config
                
          env:              
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: mango-secrets
                  key: Order__ConnectionStrings__DefaultConnection

            - name: ServiceUrls__ProductAPI
              value: http://mango-product:8080